// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisEx is an autogenerated mock type for the RedisEx type
type RedisEx struct {
	mock.Mock
}

// GetFieldValue provides a mock function with given fields: key
func (_m *RedisEx) GetFieldValue(key string) (interface{}, error) {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: loadQueryRlsEventsFunc
func (_m *RedisEx) Init(loadQueryRlsEventsFunc func(interface{}, interface{}) error) error {
	ret := _m.Called(loadQueryRlsEventsFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(interface{}, interface{}) error) error); ok {
		r0 = rf(loadQueryRlsEventsFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
