// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisEx is an autogenerated mock type for the RedisEx type
type RedisEx struct {
	mock.Mock
}

// GetFieldValue provides a mock function with given fields: key, value
func (_m *RedisEx) GetFieldValue(key string, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: loadQueryRlsEventsFunc
func (_m *RedisEx) Init(loadQueryRlsEventsFunc func(interface{}, interface{}) error) error {
	ret := _m.Called(loadQueryRlsEventsFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(interface{}, interface{}) error) error); ok {
		r0 = rf(loadQueryRlsEventsFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
